/* =====================================================================
   Y.T.M. Homes & More — content data
   Plain JS, attached to window.YTM. No build step.
   ===================================================================== */
(function () {
  const DS = "_ds/y-t-m-homes-more-design-system-3b4e5e11-a14e-4a69-a789-e8f6b6849602";

  // ---- Collections -------------------------------------------------
  const collections = {
    saranda: {
      id: "saranda",
      name: "Saranda",
      country: "Albania",
      eyebrow: "Albanian Riviera",
      tagline: "Sunny coastal stays above the blue horizon.",
      mood: "warm · coastal · slow",
      wash: "sunrise",
      letLabel: "Short-term stays · Airbnb",
      count: 3,
      pinX: 30, pinY: 78, // position on the stylised map (%)
    },
    prishtina: {
      id: "prishtina",
      name: "Prishtina",
      country: "Kosovo",
      eyebrow: "City of Kosovo",
      tagline: "Calm private bases, close to daily life.",
      mood: "urban · private · grounded",
      wash: "dusk",
      letLabel: "Long-term rentals",
      count: 2,
      pinX: 58, pinY: 30,
    },
  };

  // ---- Properties --------------------------------------------------
  const SPOTIFY = "https://open.spotify.com/playlist/6lHaz5lfEkU2Jf5cIW6VGl?si=635ef798cdd24fd6";

  const properties = [
    {
      id: "dreamy",
      collection: "saranda",
      name: "YTM Dreamy",
      kind: "Holiday apartment",
      eyebrow: "Bougainvillea Bay · Saranda",
      location: "Saranda, Albania",
      mood: "A quiet coastal stay above Saranda’s blue horizon.",
      glance: "Designed for slow mornings, sea views, and easy evenings.",
      sleeps: "Sleeps 4",
      bedrooms: "1 bedroom · 1 sofa bed",
      price: 95,
      rating: "4.94",
      reviews: 128,
      wash: "sunrise",
      accent: "sun",
      badges: [{ label: "Sea view", tone: "sea" }, { label: "Superhost", tone: "sun" }],
      airbnb: "https://airbnb.com",
      description:
        "Wake to the bay, coffee on the terrace, and the soft sound of the sea below. Dreamy is our sunniest apartment — light-filled, calm and a few minutes from the promenade. Made for unhurried days and long golden evenings.",
      amenities: [
        { icon: "waves", label: "Sea view", detail: "From terrace & bedroom" },
        { icon: "wifi", label: "Fast Wi-Fi", detail: "YTM-Dreamy" },
        { icon: "wind", label: "Air conditioning", detail: "Every room" },
        { icon: "square-parking", label: "Free parking", detail: "Gated, on-site" },
        { icon: "coffee", label: "Coffee & tea", detail: "Stocked on arrival" },
        { icon: "waves-ladder", label: "Pool access", detail: "Resort pool" },
      ],
      practical: [
        { icon: "waves", k: "Beach", v: "5 min walk" },
        { icon: "building-2", k: "Old town", v: "8 min drive" },
        { icon: "wifi", k: "Wi-Fi", v: "200 Mbps" },
        { icon: "car-front", k: "Parking", v: "On-site, free" },
        { icon: "arrow-up-down", k: "Elevator", v: "Yes" },
        { icon: "sun", k: "Aspect", v: "West, sunset" },
      ],
      checkin: [
        "Self check-in from 3:00 pm",
        "Keys in the black lockbox — code sent by WhatsApp",
        "Check-out by 11:00 am",
      ],
      rules: [
        "You’re welcome to smoke on the terrace — never inside.",
        "Quiet hours after 11 pm for our neighbours.",
        "Something broke or spilled? It happens — just tell us.",
      ],
      nearby: [
        { icon: "umbrella", k: "Mango Beach", v: "5 min" },
        { icon: "utensils", k: "Taverna Laguna", v: "7 min" },
        { icon: "ship", k: "Ksamil boats", v: "20 min" },
        { icon: "landmark", k: "Butrint ruins", v: "25 min" },
      ],
      recommendations: [
        { title: "Morning", text: "Coffee at Mare Nostrum, then a slow swim before the beach fills up." },
        { title: "Afternoon", text: "Boat to Ksamil’s little islands — clearest water on the coast." },
        { title: "Evening", text: "Sunset from the castle, dinner of grilled fish on the promenade." },
      ],
      review: {
        quote: "Spotless, calm and the sunset from the terrace is unreal. Our hosts thought of everything — it felt like staying with friends.",
        name: "Marta R.",
        meta: "Stayed July 2025 · 5 nights",
        tone: "sage",
      },
    },
    {
      id: "lovely",
      collection: "saranda",
      name: "YTM Lovely",
      kind: "Holiday apartment",
      eyebrow: "Bougainvillea Bay · Saranda",
      location: "Saranda, Albania",
      mood: "Bright, gentle and made for two.",
      glance: "Garden mornings and a short stroll to the water.",
      sleeps: "Sleeps 2",
      bedrooms: "Studio · garden side",
      price: 72,
      rating: "4.89",
      reviews: 86,
      wash: "coast",
      accent: "sage",
      badges: [{ label: "Garden", tone: "sage" }, { label: "Pool access", tone: "sea" }],
      airbnb: "https://airbnb.com",
      description:
        "A soft, sun-warmed studio opening onto the garden. Lovely is our cosiest stay — perfect for two, with everything within reach and the pool a few steps away.",
      amenities: [
        { icon: "flower-2", label: "Garden access", detail: "Shaded terrace" },
        { icon: "wifi", label: "Fast Wi-Fi", detail: "YTM-Lovely" },
        { icon: "wind", label: "Air conditioning", detail: "Studio" },
        { icon: "waves-ladder", label: "Pool access", detail: "Resort pool" },
        { icon: "coffee", label: "Coffee & tea", detail: "Stocked" },
        { icon: "square-parking", label: "Free parking", detail: "On-site" },
      ],
      practical: [
        { icon: "waves", k: "Beach", v: "7 min walk" },
        { icon: "flower-2", k: "Garden", v: "Direct access" },
        { icon: "wifi", k: "Wi-Fi", v: "200 Mbps" },
        { icon: "car-front", k: "Parking", v: "On-site, free" },
      ],
      checkin: ["Self check-in from 3:00 pm", "Keys in the lockbox by the door", "Check-out by 11:00 am"],
      rules: ["Smoking on the terrace only.", "Quiet after 11 pm.", "Tell us if anything needs fixing — we’re close by."],
      nearby: [
        { icon: "umbrella", k: "Town beach", v: "7 min" },
        { icon: "utensils", k: "Local tavernas", v: "5 min" },
        { icon: "ship", k: "Ferry to Corfu", v: "12 min" },
      ],
      recommendations: [
        { title: "Morning", text: "Breakfast in the garden, then the quiet end of the town beach." },
        { title: "Evening", text: "Aperitivo on the promenade as the lights come on." },
      ],
      review: {
        quote: "The garden was our favourite spot — quiet, green and a two-minute walk to the sea. We didn’t want to leave.",
        name: "Sofia & Luka",
        meta: "Stayed June 2025 · 4 nights",
        tone: "sage",
      },
    },
    {
      id: "horizon",
      collection: "saranda",
      name: "YTM Horizon",
      kind: "Holiday apartment",
      eyebrow: "Bougainvillea Bay · Saranda",
      location: "Saranda, Albania",
      mood: "Wide sea views, top floor, endless light.",
      glance: "The whole bay laid out beneath your terrace.",
      sleeps: "Sleeps 5",
      bedrooms: "2 bedrooms · sea terrace",
      price: 128,
      rating: "4.97",
      reviews: 64,
      wash: "sunrise",
      accent: "sea",
      badges: [{ label: "Panoramic", tone: "sea" }, { label: "Top floor", tone: "sun" }],
      airbnb: "https://airbnb.com",
      description:
        "Our highest, brightest home — two bedrooms and a long terrace facing straight out to sea. Horizon is made for families and friends who want space, light and the best view in the bay.",
      amenities: [
        { icon: "waves", label: "Panoramic sea view", detail: "Full bay" },
        { icon: "wifi", label: "Fast Wi-Fi", detail: "YTM-Horizon" },
        { icon: "wind", label: "Air conditioning", detail: "All rooms" },
        { icon: "square-parking", label: "Free parking", detail: "Gated" },
        { icon: "utensils", label: "Full kitchen", detail: "Dishwasher" },
        { icon: "waves-ladder", label: "Pool access", detail: "Resort pool" },
      ],
      practical: [
        { icon: "waves", k: "Beach", v: "6 min walk" },
        { icon: "arrow-up-down", k: "Floor", v: "Top, lift" },
        { icon: "wifi", k: "Wi-Fi", v: "200 Mbps" },
        { icon: "bed-double", k: "Beds", v: "2 + sofa" },
      ],
      checkin: ["Self check-in from 3:00 pm", "Lockbox code by WhatsApp", "Check-out by 11:00 am"],
      rules: ["Terrace smoking only.", "Quiet after 11 pm.", "Anything amiss? Message us any time."],
      nearby: [
        { icon: "umbrella", k: "Mango Beach", v: "6 min" },
        { icon: "landmark", k: "Lekuresi castle", v: "10 min" },
        { icon: "ship", k: "Ksamil boats", v: "20 min" },
      ],
      recommendations: [
        { title: "Morning", text: "Sunrise coffee on the terrace — the whole bay to yourselves." },
        { title: "Day", text: "Drive to Lekuresi for lunch with a view over two seas." },
      ],
      review: {
        quote: "The view is even better than the photos. Five of us, plenty of room, and mornings on that terrace we’ll never forget.",
        name: "The Bekteshi family",
        meta: "Stayed August 2025 · 7 nights",
        tone: "sea",
      },
    },
    {
      id: "taslixhe",
      collection: "prishtina",
      name: "YTM Taslixhe",
      kind: "Private city home",
      eyebrow: "Taslixhe · Prishtina",
      location: "Prishtina, Kosovo",
      mood: "A private city base, close to daily life but calm enough to unwind.",
      glance: "A quiet residential street, minutes from the centre.",
      sleeps: "Sleeps 4",
      bedrooms: "2 bedrooms · residential",
      price: 88,
      rating: "4.92",
      reviews: 41,
      wash: "dusk",
      accent: "stone",
      badges: [{ label: "Residential", tone: "neutral" }, { label: "Quiet street", tone: "sage" }],
      airbnb: "https://airbnb.com",
      description:
        "Set in leafy Taslixhe, this is a calm, private home a short walk from Prishtina’s cafés and centre. Grounded and well-kept — a real neighbourhood base for longer city stays.",
      amenities: [
        { icon: "wifi", label: "Fast Wi-Fi", detail: "YTM-Taslixhe" },
        { icon: "wind", label: "Heating & A/C", detail: "All rooms" },
        { icon: "square-parking", label: "Street parking", detail: "Easy, free" },
        { icon: "coffee", label: "Coffee & tea", detail: "Stocked" },
        { icon: "washing-machine", label: "Washer", detail: "In unit" },
        { icon: "tv", label: "Smart TV", detail: "Living room" },
      ],
      practical: [
        { icon: "building-2", k: "City centre", v: "10 min walk" },
        { icon: "trees", k: "Neighbourhood", v: "Taslixhe" },
        { icon: "wifi", k: "Wi-Fi", v: "300 Mbps" },
        { icon: "car-front", k: "Parking", v: "Street, free" },
        { icon: "plane", k: "Airport", v: "20 min drive" },
        { icon: "bed-double", k: "Beds", v: "2 + sofa" },
      ],
      checkin: ["Self check-in from 2:00 pm", "Smart lock code by WhatsApp", "Check-out by 11:00 am"],
      rules: ["No smoking indoors.", "Quiet after 10 pm — kind neighbours.", "Something off? Tell us, we’re nearby."],
      nearby: [
        { icon: "coffee", k: "Café Soma", v: "5 min" },
        { icon: "utensils", k: "Restaurant Tiffany", v: "8 min" },
        { icon: "landmark", k: "National Library", v: "12 min" },
        { icon: "trees", k: "Germia Park", v: "10 min drive" },
      ],
      recommendations: [
        { title: "Morning", text: "Macchiato at Soma, then a wander through the old bazaar." },
        { title: "Afternoon", text: "Walk to the National Library — Prishtina’s strangest, best building." },
        { title: "Evening", text: "Dinner on Nëna Terezë boulevard, busy and friendly." },
      ],
      review: {
        quote: "Exactly what we needed for a working week — quiet, comfortable, and ten minutes from everything. Spotless and very well managed.",
        name: "Driton K.",
        meta: "Stayed September 2025 · 6 nights",
        tone: "sage",
      },
    },
    {
      id: "center",
      collection: "prishtina",
      name: "YTM Center",
      kind: "Commercial · city centre",
      commercial: true,
      eyebrow: "City centre · Prishtina",
      location: "Prishtina, Kosovo",
      mood: "Right in the heart of the city, with everything at the door.",
      glance: "A central object, steps from the main boulevard.",
      sleeps: "Sleeps 3",
      bedrooms: "1 bedroom · central",
      price: 96,
      rating: "4.90",
      reviews: 33,
      wash: "dusk",
      accent: "stone",
      badges: [{ label: "Commercial space", tone: "neutral" }, { label: "Central", tone: "sea" }],
      airbnb: "https://airbnb.com",
      description:
        "Our most central property — a polished base right in Prishtina’s commercial heart. Step out to cafés, offices and the boulevard. Ideal for business stays and city weekends.",
      amenities: [
        { icon: "wifi", label: "Business Wi-Fi", detail: "YTM-Center" },
        { icon: "wind", label: "Heating & A/C", detail: "All rooms" },
        { icon: "briefcase", label: "Work desk", detail: "Quiet corner" },
        { icon: "coffee", label: "Coffee & tea", detail: "Stocked" },
        { icon: "arrow-up-down", label: "Elevator", detail: "Building lift" },
        { icon: "tv", label: "Smart TV", detail: "Living room" },
      ],
      practical: [
        { icon: "building-2", k: "Boulevard", v: "2 min walk" },
        { icon: "briefcase", k: "Best for", v: "Business" },
        { icon: "wifi", k: "Wi-Fi", v: "300 Mbps" },
        { icon: "arrow-up-down", k: "Elevator", v: "Yes" },
        { icon: "plane", k: "Airport", v: "18 min drive" },
      ],
      checkin: ["Self check-in from 2:00 pm", "Reception holds keys 24h", "Check-out by 11:00 am"],
      rules: ["No smoking indoors.", "Quiet after 10 pm.", "Need anything for work? Just ask."],
      nearby: [
        { icon: "coffee", k: "Half & Half", v: "2 min" },
        { icon: "utensils", k: "Restaurants", v: "On the street" },
        { icon: "landmark", k: "Newborn monument", v: "6 min" },
        { icon: "shopping-bag", k: "Grand Store", v: "4 min" },
      ],
      recommendations: [
        { title: "Morning", text: "Coffee downstairs, emails done before the city wakes up." },
        { title: "Evening", text: "The whole centre is yours on foot — pick a corner and stay a while." },
      ],
      review: {
        quote: "Perfect location for work — I walked to every meeting. Clean, central and the host was instantly responsive.",
        name: "Arta M.",
        meta: "Stayed October 2025 · 3 nights",
        tone: "sage",
      },
    },
  ];

  const byId = {};
  properties.forEach((p) => { byId[p.id] = p; });

  // ---- Our story (homepage) ----------------------------------------
  const story = {
    eyebrow: "Our story",
    title: "A name built from ours.",
    paragraphs: [
      "Y.T.M. is our parents, Ylber and Teuta, and the initial of our family name. They are the investors behind every property here: a lifetime of careful work, built into lovely homes they have always kept with care.",
      "Our mother Teuta, an architect, helped design these properties down to their very foundations. It is why each one feels considered, solid and quietly beautiful.",
      "Today the two of us, Lorik and Leart, manage the spaces for rent: the Saranda apartments as short-term stays on Airbnb, and the Prishtina homes as long-term rentals. More family properties are taking shape, and they will join when they are ready.",
    ],
    signoff: "Lorik & Leart",
  };

  window.YTM = {
    DS,
    ASSETS: "assets",
    SPOTIFY,
    collections,
    properties,
    byId,
    story,
    propsOf: (cid) => properties.filter((p) => p.collection === cid),
    contact: {
      whatsapp: "+355 69 000 0000",
      email: "stay@ytmhomes.com",
      instagram: "@ytm.homes",
      host: "Lorik & Leart",
    },
  };
})();
